language: c
branches:
  except:
    - refactoring
  only:
    - master
    - dev
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i *.deb
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-latex-base
  - sudo apt-get install -y texlive-font-utils
  - sudo apt-get install -y texlive-latex-recommended
  - sudo apt-get install -y texlive-fonts-recommended
  - sudo apt-get install -y texlive-latex-extra
  - sudo apt-get install -y python-pip
  - sudo pip install pandoc-latex-environment
  - cpanm Etherpad Config::YAML URI::Encode
notifications:
  irc:
    channels:
      - "chat.freenode.net#pressecitron"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url} Build details : %{build_url}"
      - "%{commit_message}"
    use_notice: true
script:
  - ./build.sh
  - ./test_cocktail_01 && ./test_cocktail_02 && ./test_cocktail_03

