language: perl
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y liblwp-protocol-https-perl
  - sudo apt-get install -y starman
  - sudo apt-get install -y pandoc
  - sudo apt-get install -y pandoc-citeproc
  - sudo apt-get install -y cabal-install
  - "cabal update"
  - "cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)"
  - "cpanm Moo"
  - "cpanm Pandoc"

script:
  - ./test_pandoc_version.sh
  - perl -MPandoc -E 'say $Pandoc::VERSION'

