language: perl
sudo: required
branches:
  except:
    - refactoring
    - dev
  only:
    - master
notifications:
  irc:
    channels:
      - "chat.freenode.net#pressecitron"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url} Build details : %{build_url}"
      - "%{commit_message}"
    use_notice: true
install:
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i *.deb
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-latex-base texlive-font-utils texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
  - sudo apt-get install -y python-pip
  - sudo pip install pandoc-latex-environment
  - cpanm --notest Config::YAML Encode URI::Encode LWP::UserAgent LWP::Protocol::https Etherpad
  - sudo ./build.sh
script:
  - t/alltests
