#!/bin/bash

printf "$PRINTFPATTERN" $0 : "Lancement avec un dossier manquant"

URL_BASE=https%3A%2F%2Fpad.exegetes.eu.org%2Fp%2Fg.DSXI1kGFT1gjor66%24Abro-REP-Tele2-Principal%2Fexport%2Ftxt
URL_GARDE=https%3A%2F%2Fpad.exegetes.eu.org%2Fp%2Fg.DSXI1kGFT1gjor66%24Abro-REP-Tele2-Garde%2Fexport%2Ftxt
PROJET=Projet$$

OUTPUT=$(./cocktail -v \
           -p "$PROJET" \
           -b "$URL_BASE" \
           -g "$URL_GARDE" 2>&1 >/dev/null) 
RC=$?
echo -n "RC=$RC "
_check_return 10 "$RC"
exit "$RC"
